grimoirelab_repo: "https://gitlab.com/jsmanrique/grimoirelab-for-demos"
src_settings_path: "../grimoirelab-settings/"
dest_settings_path: "./grimoirelab-settings"
update_orgs: true
update_settings: true
user: root
dest_path: /{{user if (user == "root") else ["home",user]|join("/")}}/{{ grimoirelab_repo.split("/")[-1] }}
gcp_cos: false