---
- name: Setting up connection
  hosts: all
  remote_user: root
  tasks:
    - name: Clone GrimoireLab Analytics repo
      git:
        repo: 'https://gitlab.com/jsmanrique/grimoirelab-with-opendistro.git'
        dest: /root/grimoirelab-with-opendistro/
        force: yes
        recursive: yes
        track_submodules: yes