---
- hosts: all
  remote_user: "{{ user }}"   
  tasks:
    - name: Set sysctl
      command: sudo sysctl -w vm.max_map_count=262144

    - name: Clone GrimoireLab repo
      git:
        repo: "{{ grimoirelab_repo }}"
        dest: "{{ dest_path }}"
        track_submodules: true
        force: yes
    
    - name: Set down running GrimoireLab containers
      command: docker-compose down
      args:
        chdir: "{{ dest_path }}"
      when: ansible_os_family != "Container-Optimized OS"
    
    - name: Set down GrimoireLab containers in GCP Containers Optimized instance
      command: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v {{ dest_path }}:{{ dest_path }} -w={{ dest_path }} docker/compose:1.24.1 down
      args:
        chdir: "{{ dest_path }}"
      when: ansible_os_family == "Container-Optimized OS"

    - import_tasks: upload-settings.yml

    - name: Start GrimoireLab containers
      command: docker-compose up -d
      args:
        chdir: "{{ dest_path }}"
      # register: output
      when: ansible_os_family != "Container-Optimized OS"
    
    - name: Start GrimoireLab containers in GCP Containers Optimized instance
      command: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v {{ dest_path }}:{{ dest_path }} -w={{ dest_path }} docker/compose:1.24.1 up -d
      args:
        chdir: "{{ dest_path }}"
      # register: output
      when: ansible_os_family == "Container-Optimized OS"
    
    # - debug:
    #     var: output