---
- hosts: all
  remote_user: "{{ user }}"
  tasks:
        
    - import_tasks: upload-settings.yml
    - import_tasks: update-organizations.yml
    
    - name: Restart containers
      command: docker-compose restart
      args:
        chdir: "{{ dest_path }}"
      register: output
      when: ansible_os_family != "Container-Optimized OS"
    
    - name: Restart containers in GCP COS VM
      command: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.24.1 restart
      args:
        chdir: "{{ dest_path }}"
      register: output
      when: ansible_os_family == "Container-Optimized OS"
    
    - debug:
        var: output