- name: Upload new GrimoireLab settings
  copy: 
    src: "{{ src_settings_path }}/{{ item }}"
    dest: /{{user if (user == "root") else ["home",user]|join("/")}}/{{ grimoirelab_repo.split("/")[-1] }}/{{ dest_settings_path }}
  with_items:
    - setup.cfg
    - projects.json
  when: update_settings