- name: Upload new GrimoireLab settings
  copy: 
    src: "{{ src_settings_path }}/{{ item }}"
    dest: "{{ dest_path }}/{{ dest_settings_path }}"
  with_items:
    - setup.cfg
    - projects.json
  when: update_settings